FROM python:3.11-slim

WORKDIR /app

COPY requirements_inference_api.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY main.py ./
COPY predict.py ./

RUN apt-get update && apt-get install -y curl   

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]