apiVersion: v1
data:
  init_mlflow.sql: |-
    CREATE DATABASE IF NOT EXISTS mlflow_db;

    GRANT ALL PRIVILEGES ON mlflow_db.*
    TO 'mlops_user'@'%';

    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql-db
  name: mysql-db-cm1
