apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config

data:
  MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  MYSQL_HOST: "mysql_db"
  MYSQL_PORT: "3306"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  MLFLOW_EXPERIMENT: "diabetes_readmission"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "mlflow-artifacts"
  API_BASE_URL: "http://fastapi:8003"
  MODEL_NAME: "diabetes_catboost_model"
  MODEL_ALIAS: "champion"
  API_URL: "http://api-inference:8001"
  LOCUST_HOST: "http://api-inference:8001"

---

apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets

type: Opaque

stringData:
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "supersecret"

  MYSQL_DATABASE: "mlops_db"
  MYSQL_USER: "mlops_user"
  MYSQL_PASSWORD: "mlops_pass"
  MYSQL_ROOT_PASSWORD: "root"

  RAW_TABLE: "raw_diabetes_data"
  CLEAN_TABLE: "clean_diabetes_data"
  SPLIT_TABLE: "dataset_split"

  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "supersecret"
  MINIO_SECRET_KEY: "supersecret"

  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin"