apiVersion: apps/v1
kind: Deployment

metadata:
  name: airflow-scheduler

spec:
  replicas: 1

  selector:
    matchLabels:
      app: airflow-scheduler

  template:
    metadata:
      labels:
        app: airflow-scheduler

    spec:
      containers:
        - name: airflow-scheduler

          image: karabaharesu/mlops-airflow:latest
          imagePullPolicy: Always

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "768Mi"
              cpu: "1000m"

          command:
            - airflow

          args:
            - scheduler

          envFrom:
            - configMapRef:
                name: mlops-config
            - secretRef:
                name: mlops-secrets

          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor

            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow

            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://airflow:airflow@postgres/airflow

            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://redis:6379/0

            - name: AIRFLOW__CORE__FERNET_KEY
              value: ""

            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"

            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

            - name: PYTHONPATH
              value: /opt/airflow

            - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
              value: /opt/airflow/logs

            - name: AIRFLOW__LOGGING__REMOTE_LOGGING
              value: "False"

          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs

      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc