apiVersion: batch/v1
kind: Job

metadata:
  name: airflow-init

spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: airflow-init

          image: karabaharesu/mlops-airflow:latest

          command:
            - /bin/bash
            - -c

          args:
            - |
              airflow db migrate && \
              airflow users create \
              --username airflow \
              --password airflow \
              --firstname Admin \
              --lastname User \
              --role Admin \
              --email admin@example.com

          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor

            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow

            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://airflow:airflow@postgres/airflow

            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://redis:6379/0

            - name: AIRFLOW__CORE__FERNET_KEY
              value: ""

            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"

            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

            - name: PYTHONPATH
              value: /opt/airflow