apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-inference

  labels:
    io.kompose.service: api-inference

spec:
  replicas: 1

  selector:
    matchLabels:
      io.kompose.service: api-inference

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        io.kompose.service: api-inference

    spec:
      containers:

        - name: api-inference

          image: karabaharesu/api-inference:2.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8001
              protocol: TCP

          envFrom:
            - configMapRef:
                name: mlops-config
            - secretRef:
                name: mlops-secrets

          volumeMounts:
            - mountPath: /app/logs
              name: api-inference-claim2

      restartPolicy: Always

      volumes:
        - name: api-inference-claim2
          persistentVolumeClaim:
            claimName: api-inference-claim2