apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: streamlit-ui
  name: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit-ui
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-k8s.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: streamlit-ui
    spec:
      containers:
        - image: karabaharesu/streamlit-ui:1.0
          name: streamlit-ui
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"

            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8501
              protocol: TCP
      restartPolicy: Always
